default: &default
  adapter: postgresql
  encoding: unicode
  pool: "<%= ENV.fetch('MAX_THREADS', 5) %>"
  port: "<%= ENV.fetch('POSTGRES_PORT', '5432') %>"
  username: "<%= ENV.fetch('POSTGRESQL_USERNAME', 'postgres') %>"
  password: "<%= ENV.fetch('POSTGRESQL_PASSWORD', 'password') %>"

development:
  <<: *default
  database: feeback_app_development

test:
  <<: *default
  database: feeback_app_test

production:
  <<: *default
  database: feedback_app_production
